name: Deploy to npm

on:
  push:
    branches: master

jobs:
  setup:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ '10.x' }}
          registry-url: 'https://registry.npmjs.org'
      - run: npm install 

  lint:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: npm run lint

  test:
    needs: [setup ]
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: npm run test  
        
  deploy:
    needs: [setup, lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: npm run build
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
