  
name: Test

on:
  pull_request:
    branches: 
      - master
  push:
   branches-ignore:
   - master

jobs:
  Run Tests:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ '10.x' }}
          registry-url: 'https://registry.npmjs.org'
      - run: npm install 
      - name: Check Format
        run: npm run check-format
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test 
